- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    options: '-pl webgoat-server spring-boot:run'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false